### ISSUE TITLE
Massive spouts of errors on the 1.18.X version

### ISSUE THREAD

**Issue by McMonkey26** [tierrif/chat-utils#12]
I'm trying to code a copy chat mod of my own for fabric 1.18, so I downloaded your mod to see how it worked, and take some inspiration from the coding you've done, but when I logged into a new world, it wouldn't load, and was stuck on the 100% screen for upwards of 2 minutes. I reloaded minecraft, with the logs open, and was immediately hit with 10k errors in less than 5 seconds of loading. I'd attach the log files, but they are 12 and 78 megabytes, respectively.

the error
[01:51:26] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
	at net.minecraft.class_634.method_38539(class_634.java:661) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:656) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]

**Comment by tierrif** [comment]
Hi, try base off this commit: https://github.com/tierrif/chat-utils/tree/b0e13c832242dbf542a958f118d065a9792b962a

The 1.19 version has many changes from 1.18 and is untested on any older version.

**Comment by tierrif** [comment]
Closed for inactivity. Re-open a new issue if you find additional problems.
