### ISSUE TITLE
[Bug] Don't know how to parse #FF913DE2 at $.color 

### ISSUE THREAD

**Issue by Darkcarnage23** [tierrif/chat-utils#25]
Seems to just happen when a message in chat gets sent specifically
Version: 1.9.1 for 1.20.1
Error msg: https://mclo.gs/K1BgpNj

**Comment by retrixe** [comment]
Your server is sending invalid colour codes to the client. Will try to add a failsafe for this, but yeah, not ideal behaviour for servers to partake in

Relevant portions from the log:

>>> 	at io.github.hotlava03.chatutils.util.StringUtils.textToLegacy(StringUtils.java:39) ~[chat-utils-1.9.1+1.20.1.jar:?]
	at io.github.hotlava03.chatutils.listeners.InjectChatCopyListener.accept(InjectChatCopyListener.java:21) ~[chat-utils-1.9.1+1.20.1.jar:?]

**Comment by retrixe** [comment]
@Darkcarnage23 the code in the mod changed drastically with 1.10.0, please try the latest version of the mod on this server (test copying messages specifically, the error should be gone when simply receiving messages now), and see if this issue persists
