### ISSUE TITLE
Chat messages dissapearing

### ISSUE THREAD

**Issue by yatesy34** [tierrif/chat-utils#50]
**Describe the bug**
After sending/receiving the same message, I get a lag spike and they both dissapear

**To Reproduce**
1. Join a server
2. Send an identical message
3. See bug

**Expected behavior**
A lag spike for around 0.5-1 seconds, then chat messages dissapearing

**Client information**
 - OS: macOS: Sonoma 14.1.1
 - Minecraft: Fabric 1.20.4
 - Mod version: 1.10.3+1.20.4
 - Other mods: Accurate Block placement v1.2.1, AutoRelog v0.0.7+1.20.4, Boosted Brightness v2.2.0, CIT Resawn v1.1.4+1.20.4, Continuity v3.0.0-beta.4+1.20.2, FPS-Display v4.0.0+1.20.4. FreeCam v2.2.1+1.20.4, Indium v1.0.30+mc1.20.4, Logical Zoom v0.0.22. Mod Menu v9.0.0, No Fog v1.3.5+1.16.5-1.20.4, Sodium v0.5.8+mc1.20.4, WorldEdit v7.3.0-beta-04+c28ebca

**Video**
https://github.com/tierrif/chat-utils/assets/173083867/81d6f62f-2abb-4d33-a132-5de92d002400

**Additional context**
Haven't had this issue all the time I've used this mod, only started a few days ago

**Comment by Cinder4198** [comment]
I've also been having this issue, this gets thrown into logs whenever the anti spam filter fails.

```
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:268) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_5250.method_10852(class_5250.java:57) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_5250.method_27693(class_5250.java:53) ~[minecraft-1.20.4.i0:0/:?]
	at io.github.hotlava03.chatutils.listeners.AntiSpamListener.accept(AntiSpamListener.java:94) ~[chat-utils-1.10.31.20.4.i0:0/:?]
	at io.github.hotlava03.chatutils.events.ReceiveMessageCallback.lambda$static$0(ReceiveMessageCallback.java:15) ~[chat-utils-1.10.31.20.4.i0:0/:?]
	at net.minecraft.class_338.handler$ckp000$chat-utils$addMessage(class_338.java:1573) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_338.method_44811(class_338.java) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_338.method_1812(class_338.java:206) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_7594.method_44736(class_7594.java:196) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_634.method_43596(class_634.java:869) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:20) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:7) ~[minecraft-1.20.4.i0:0/:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[minecraft-1.20.4.i0:0/:?]
	... 12 more
```

OS: Linux Mint 21.2 Cinnamon
Minecraft Version: Minecraft 1.20.4, Quilt 0.24.0
Mod Version: 1.10.3+1.20.4

Other Mods: 
Architectury 11.0.12, Better Sodium Video Settings Button 3.0.3, BetterF3 9.0.2, Borderless Mining 1.1.9+1.20.2, CIT Resewn 1.1.4+1.20.4, Concurrent Chunk Management Engine 0.2.0+alpha.11.58, Continuity 3.0.0-beta.4+1.20.2, CraftPresence 2.3.5, Custom Window Title 1.2.0, Dynamic FPS 3.4.2, Entity Model Features 1.3, Entity Texture Features 5.2.3, EntityCulling 1.6.3.1, Indium 1.0.30+mc1.20.4, Lazy DFU 0.1.3, Lithium 0.12.1, Memory Leak Fix 1.1.5, MinecraftCapes 12.3.7, Mod Menu 9.0.0, ModernFix 5.15.0+mc1.20.4, my-beloved-icon 1.0-SNAPSHOT, No Chat Reports 1.20.4-2.5.0, Nostalgic Tweaks 2.0.0-Beta-9.0, NotEnoughAnimations 1.7.1, Ok Zoomer 6.0.0, perspektive 1.3.4, Recursive Resources 2.5.2+1.20.4, Simple Voice Chat 1.20.4-2.5.9, Sneak Tweak 1.10.1, Sodium 0.5.8+mc1.20.4, Sound Physics Remastered 1.20.4-1.3.1, Tooltip Scroll 1.3.0, ViaFabric 0.4.13+64-main

**Comment by tierrif** [comment]
Thanks for your report. Unfortunately, given how busy I'm becoming in real life, maintaining this mod is becoming impossible. I wouldn't mind having someone take over at this point, or I'll simply end up having to shut it down.

I currently have no time to look into the current issues but I'm more than fine to review PRs as soon as I can and publish new mod versions, so we'll see if anyone contributes. If not, I'll post mod alternatives and archive this repo.

Thanks for understanding.

**Comment by Jes-debug** [comment]
im sorry to hear maintaining this mod is becoming impossible D:

**Comment by Endertective** [comment]
this started happening to me after i switched to 1.20.4, in 1.20.1 it worked as usual

**Comment by tierrif** [comment]
Possibly fixed after the new version, open a new issue if this persists
